{
 "title": "Project2",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate(apiserver_request_total{job=\"apiserver\",code!~\"5..\"}[5m]))/sum (rate(apiserver_request_total{job=\"apiserver\"}[5m]))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\",code=~\"2..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\"}[5m])) by (le, verb))"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": " 1 - ((1 - (sum(increase(apiserver_request_total{job=\"apiserver\", code=\"200\"}[7d])) by (verb)) / sum(increase(apiserver_request_total{job=\"apiserver\"}[7d])) by (verb)) / (1 - .80))"
    }
   ]
  }
 ]
}